name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ubuntu
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:/app/telegram-server/
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd /app/telegram-server/
          source .venv/bin/activate
          uv pip install -r requirements.txt
          pm2 reload aws/ecosystem.config.js --update-env
        '

    - name: Cleanup
      run: rm -f private_key
